version: '2'
services:
  bot:
    build: .
    image: kenrisa/discord-rustserverstatus
    container_name: discord-rustserverstatus
    restart: unless-stopped
    environment:
      - debug=true
      - token=76561197960265728
      - apiSite=4
      - apiUrl=https://rust.com
      - enableRcon=0
      - serverIp=
      - serverPort=5353
      - rconhost=192.168.30.53
      - rconport=5354
      - rconpass=Cmdx@2025
      - prefix=!
      - "roles=Administrator, admins"
      - "queueMessage=currently waiting in queue"
      - updateInterval=3
